### PR TITLE
Add Plug to Home Page

### PR DESCRIPTION
**Pull request by jabbate19**
I saw #83 , and after talking to @Cbturtle2 decided I will work on it.

### CODE REVIEW

**Comment by mxmeinhold** [comment]
Why all the merge commits? Are you not based on develop?

**Comment by jabbate19** [comment]
Git oof, fixed

**Comment by mxmeinhold** [comment]
Can you dm me a screenshot of what this looks like?

**Comment by jabbate19** [comment]
image (3)

**Pull request merged**
