### PR TITLE
Update Versions in requirements.txt

### PR DESCRIPTION
**Pull request by jabbate19**
Some background installs broke the gallery install in pip. This sets
everything directly as set on prod. This makes development and future
rollouts possible without fail.

### CODE REVIEW

**Comment by devinmatte** [comment]
Personally think that using something like https://github.com/jazzband/pip-tools is going to result in a cleaner development/prod freeze setup and makes sure we don't have any extraneous dependencies ending up in the freeze from the container. 

I'll let current people make the call on this though

**Review by WillNilges — APPROVED** [review]
🛳

**Comment by WillNilges** [comment]
I agree with Devin, but if this would work for now, then we can open an issue to manage our dependencies better?

**Comment by jabbate19** [comment]
If this is to be approved, we should make sure this immediately goes into master as well. There are commits waiting to be rolled into OKD and it its done without this PR it will not start

**Pull request merged**
